version: '3'
services:
  web:
    build: .
    ports:
     - "127.0.0.1:8000:8000"
    volumes:
     - ./:/app/
     - honda_box:/data/boxes
    tmpfs:
     - /tmp
  redis:
    image: "redis:alpine"
    volumes:
     - redis_data:/data
volumes:
  honda_box:
  redis_data:
