version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - ${DEBUGMOUNT}
     - honda_box:/data
    tmpfs:
     - /tmp
  redis:
    image: "redis:alpine"
    volumes:
     - redis_data:/data
volumes:
  honda_box:
  redis_data:
